### ISSUE TITLE
Retro tag template doesn't work well with Auto tag template

### ISSUE THREAD

**Issue by cherylf** [GorillaStack/retro-tag#4]
Hi

If Retro tag relies on Auto tag, then the CloudFormation template doesn't reflect this dependency because I compared the CloudFormation templates for both projects and it seems to me that the difference between the autotag-main template and the retrotag-main template is the permission of the Lambda execution role and the permission to invoke Lambda via SNS. So would you mind to update the readme guide to tell users how to deploy the CloudFormation templates for both projects? Thanks!

**Comment by rayj-pgi** [comment]
The readme has all of the info on how to deploy. You don't need to compare the templates as they are supposed to be different. The retro-tag project doesn't use SNS so that isn't required.

Did you follow the readme and do you have a stack called 'AutoTagRetro' with the code from the AutoTag project?

Did you extract your Cloudtrail logs using Athena to a CSV and then run the 'retro_tag.rb' script like is detailed in the README?
